### ISSUE TITLE
Black frames every now and then, sync issue

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [MarcStan/monogame-framework-wpfinterop#27] opened 2021-08-18 07:51 UTC
Hi there @MarcStan,

I too thought the black flickering where gone for good by updating to MonoGame 3.8. Unfortunately it is still there.

You can see it when rendering complex scenes. For example, when I run the WpfCore5-Demo > "Show multiple msaa scenes" with Intel Graphics, flickering appears every now and then in the two lower areas.

Any ideas?

Cheers,
Georg

**Comment by georg-eckert-zeiss** [comment] 2021-08-18 08:05
It's only a black frame every now and then. Unfortunately I could not get it to happen with this massive MSAA Scene:

```csharp
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using MonoGame.Framework.WpfInterop;
using MonoGame.Framework.WpfInterop.Input;
using System.Windows;
using WpfTest.Components;

namespace WpfTest.Scenes
{
    /// <summary>
    /// Displays content that heavily benefits from msaa (or any sort of filtering really) and lets the user toggle msaa on and off.
    /// </summary>
    public class MsaaScene : WpfGame
    {
        private BasicEffect _basicEffect;
        private WpfKeyboard _keyboard;
        private KeyboardState _keyboardState;
        private Matrix _projectionMatrix;
        private VertexBuffer _vertexBuffer;
        private VertexDeclaration _vertexDeclaration;
        private Matrix _viewMatrix;
        private Matrix _worldMatrix;
        private bool _disposed;

        private float _rotation;
        private RasterizerState _wireframe;
        private RasterizerState _filled;
        private TextComponent _msaaMessage;
        private WpfGraphicsDeviceService _graphicsDeviceService;

        protected override void Initialize()
        {
            _disposed = false;
            _graphicsDeviceService = new WpfGraphicsDeviceService(this)
            {
                PreferMultiSampling = true
            };
            Components.Add(new FpsComponent(this));
            Components.Add(new TimingComponent(this));
            _msaaMessage = new TextComponent(this, GetMsaaMessage(), new Vector2(1, 0), HorizontalAlignment.Right);
            Components.Add(_msaaMessage);

            float tilt = MathHelper.ToRadians(0);  // 0 degree angle
                                                   // Use the world matrix to tilt the cube along x and y axes.
            _worldMatrix = Matrix.CreateRotationX(tilt) * Matrix.CreateRotationY(tilt);
            _viewMatrix = Matrix.CreateLookAt(new Vector3(150, 0, 150), new Vector3(0, 75, 0), Vector3.Up);

            _basicEffect = new BasicEffect(GraphicsDevice);

            _basicEffect.World = _worldMatrix;
            _basicEffect.View = _viewMatrix;
            RefreshProjection();

            // primitive color
            _basicEffect.AmbientLightColor = new Vector3(0.1f, 0.1f, 0.1f);
            _basicEffect.DiffuseColor = new Vector3(1.0f, 1.0f, 1.0f);
            _basicEffect.SpecularColor = new Vector3(0.25f, 0.25f, 0.25f);
            _basicEffect.SpecularPower = 5.0f;
            _basicEffect.Alpha = 1.0f;

            // get a bunch of white cubes
            _basicEffect.LightingEnabled = false;

            _filled = new RasterizerState
            {
                CullMode = CullMode.None,
                FillMode = FillMode.Solid
            };
            _wireframe = new RasterizerState
            {
                CullMode = CullMode.None,
                FillMode = FillMode.WireFrame
            };

            SetupCube();

            _keyboard = new WpfKeyboard(this);

            base.Initialize();
        }

        private string GetMsaaMessage() => $"MSAA is {(_graphicsDeviceService.PreferMultiSampling ? "On" : "Off")}, press space to toggle";

        private void SetupCube()
        {
            _vertexDeclaration = new VertexDeclaration(
                new VertexElement(0, VertexElementFormat.Vector3, VertexElementUsage.Position, 0),
                new VertexElement(12, VertexElementFormat.Vector3, VertexElementUsage.Normal, 0),
                new VertexElement(24, VertexElementFormat.Vector2, VertexElementUsage.TextureCoordinate, 0)
            );

            Vector3 topLeftFront = new Vector3(-1.0f, 1.0f, 1.0f);
            Vector3 bottomLeftFront = new Vector3(-1.0f, -1.0f, 1.0f);
            Vector3 topRightFront = new Vector3(1.0f, 1.0f, 1.0f);
            Vector3 bottomRightFront = new Vector3(1.0f, -1.0f, 1.0f);
            Vector3 topLeftBack = new Vector3(-1.0f, 1.0f, -1.0f);
            Vector3 topRightBack = new Vector3(1.0f, 1.0f, -1.0f);
            Vector3 bottomLeftBack = new Vector3(-1.0f, -1.0f, -1.0f);
            Vector3 bottomRightBack = new Vector3(1.0f, -1.0f, -1.0f);

            Vector2 textureTopLeft = new Vector2(0.0f, 0.0f);
            Vector2 textureTopRight = new Vector2(1.0f, 0.0f);
            Vector2 textureBottomLeft = new Vector2(0.0f, 1.0f);
            Vector2 textureBottomRight = new Vector2(1.0f, 1.0f);

            Vector3 frontNormal = new Vector3(0.0f, 0.0f, 1.0f);
            Vector3 backNormal = new Vector3(0.0f, 0.0f, -1.0f);
            Vector3 topNormal = new Vector3(0.0f, 1.0f, 0.0f);
            Vector3 bottomNormal = new Vector3(0.0f, -1.0f, 0.0f);
            Vector3 leftNormal = new Vector3(-1.0f, 0.0f, 0.0f);
            Vector3 rightNormal = new Vector3(1.0f, 0.0f, 0.0f);

            var cubeVertices = new VertexPositionNormalTexture[36];

            // Front face.
            cubeVertices[0] = new VertexPositionNormalTexture(topLeftFront, frontNormal, textureTopLeft);
            cubeVertices[1] = new VertexPositionNormalTexture(bottomLeftFront, frontNormal, textureBottomLeft);
            cubeVertices[2] = new VertexPositionNormalTexture(topRightFront, frontNormal, textureTopRight);
            cubeVertices[3] = new VertexPositionNormalTexture(bottomLeftFront, frontNormal, textureBottomLeft);
            cubeVertices[4] = new VertexPositionNormalTexture(bottomRightFront, frontNormal, textureBottomRight);
            cubeVertices[5] = new VertexPositionNormalTexture(topRightFront, frontNormal, textureTopRight);

            // Back face.
            cubeVertices[6] = new VertexPositionNormalTexture(topLeftBack, backNormal, textureTopRight);
            cubeVertices[7] = new VertexPositionNormalTexture(topRightBack, backNormal, textureTopLeft);
            cubeVertices[8] = new VertexPositionNormalTexture(bottomLeftBack, backNormal, textureBottomRight);
            cubeVertices[9] = new VertexPositionNormalTexture(bottomLeftBack, backNormal, textureBottomRight);
            cubeVertices[10] = new VertexPositionNormalTexture(topRightBack, backNormal, textureTopLeft);
            cubeVertices[11] = new VertexPositionNormalTexture(bottomRightBack, backNormal, textureBottomLeft);

            // Top face.
            cubeVertices[12] = new VertexPositionNormalTexture(topLeftFront, topNormal, textureBottomLeft);
            cubeVertices[13] = new VertexPositionNormalTexture(topRightBack, topNormal, textureTopRight);
            cubeVertices[14] = new VertexPositionNormalTexture(topLeftBack, topNormal, textureTopLeft);
            cubeVertices[15] = new VertexPositionNormalTexture(topLeftFront, topNormal, textureBottomLeft);
            cubeVertices[16] = new VertexPositionNormalTexture(topRightFront, topNormal, textureBottomRight);
            cubeVertices[17] = new VertexPositionNormalTexture(topRightBack, topNormal, textureTopRight);

            // Bottom face.
            cubeVertices[18] = new VertexPositionNormalTexture(bottomLeftFront, bottomNormal, textureTopLeft);
            cubeVertices[19] = new VertexPositionNormalTexture(bottomLeftBack, bottomNormal, textureBottomLeft);
            cubeVertices[20] = new VertexPositionNormalTexture(bottomRightBack, bottomNormal, textureBottomRight);
            cubeVertices[21] = new VertexPositionNormalTexture(bottomLeftFront, bottomNormal, textureTopLeft);
            cubeVertices[22] = new VertexPositionNormalTexture(bottomRightBack, bottomNormal, textureBottomRight);
            cubeVertices[23] = new VertexPositionNormalTexture(bottomRightFront, bottomNormal, textureTopRight);

            // Left face.
            cubeVertices[24] = new VertexPositionNormalTexture(topLeftFront, leftNormal, textureTopRight);
            cubeVertices[25] = new VertexPositionNormalTexture(bottomLeftBack, leftNormal, textureBottomLeft);
            cubeVertices[26] = new VertexPositionNormalTexture(bottomLeftFront, leftNormal, textureBottomRight);
            cubeVertices[27] = new VertexPositionNormalTexture(topLeftBack, leftNormal, textureTopLeft);
            cubeVertices[28] = new VertexPositionNormalTexture(bottomLeftBack, leftNormal, textureBottomLeft);
            cubeVertices[29] = new VertexPositionNormalTexture(topLeftFront, leftNormal, textureTopRight);

            // Right face.
            cubeVertices[30] = new VertexPositionNormalTexture(topRightFront, rightNormal, textureTopLeft);
            cubeVertices[31] = new VertexPositionNormalTexture(bottomRightFront, rightNormal, textureBottomLeft);
            cubeVertices[32] = new VertexPositionNormalTexture(bottomRightBack, rightNormal, textureBottomRight);
            cubeVertices[33] = new VertexPositionNormalTexture(topRightBack, rightNormal, textureTopRight);
            cubeVertices[34] = new VertexPositionNormalTexture(topRightFront, rightNormal, textureTopLeft);
            cubeVertices[35] = new VertexPositionNormalTexture(bottomRightBack, rightNormal, textureBottomRight);

            _vertexBuffer = new VertexBuffer(GraphicsDevice, _vertexDeclaration, cubeVertices.Length, BufferUsage.None);
            _vertexBuffer.SetData(cubeVertices);
        }

        protected override void Dispose(bool disposing)
        {
            if (_disposed)
                return;

            Components.Clear();
            _disposed = true;

            _vertexBuffer.Dispose();
            _vertexBuffer = null;

            _vertexDeclaration.Dispose();
            _vertexDeclaration = null;

            _basicEffect.Dispose();
            _basicEffect = null;

            base.Dispose(disposing);
        }

        /// <summary>
        /// Update projection matrix values, both in the calculated matrix <see cref="_projectionMatrix"/> as well as
        /// the <see cref="_basicEffect"/> projection.
        /// </summary>
        private void RefreshProjection()
        {
            _projectionMatrix = Matrix.CreatePerspectiveFieldOfView(
                MathHelper.ToRadians(45), // 45 degree angle
                (float)GraphicsDevice.Viewport.Width /
                (float)GraphicsDevice.Viewport.Height,
                1.0f, 1000.0f);
            _basicEffect.Projection = _projectionMatrix;
        }

        protected override void Update(GameTime gameTime)
        {
            var previousKeyboardState = _keyboardState;
            _keyboardState = _keyboard.GetState();

            if (_keyboardState.IsKeyDown(Keys.Space) &&
                previousKeyboardState.IsKeyUp(Keys.Space))
            {
                _graphicsDeviceService.PreferMultiSampling = !_graphicsDeviceService.PreferMultiSampling;
                _graphicsDeviceService.ApplyChanges();

                _msaaMessage.Text = GetMsaaMessage();

            }
            base.Update(gameTime);
        }

        protected override void Draw(GameTime time)
        {
            //The projection depends on viewport dimensions (aspect ratio).
            // Because WPF controls can be resized at any time (user resizes window)
            // we need to refresh the values each draw call, otherwise cube will look distorted to user
            RefreshProjection();

            GraphicsDevice.Clear(Color.CornflowerBlue);
            GraphicsDevice.DepthStencilState = new DepthStencilState
            {
                DepthBufferEnable = true
            };
            GraphicsDevice.SetVertexBuffer(_vertexBuffer);

            // Rotate cube around up-axis.
            // only update cube when the game is active
            if (IsActive)
                _rotation += (float)time.ElapsedGameTime.TotalMilliseconds / 10000 * MathHelper.TwoPi;

            DrawCubes(_filled, Color.White);
            DrawCubes(_wireframe, Color.Black);

            base.Draw(time);
        }

        private void DrawCubes(RasterizerState rasterizerState, Color color)
        {
            GraphicsDevice.RasterizerState = rasterizerState;
            const float cubeSeperaration = 4;
            const int cubesPerRow = 50;
            _basicEffect.DiffuseColor = color.ToVector3();

            var offset = new Vector3(cubeSeperaration * cubesPerRow / 2, 0, cubeSeperaration * cubesPerRow / 2);
            // really bad performance, could use instancing to improve performance a lot
            for (int z = 0; z < cubesPerRow; z++)
            {
                for (int y = 0; y < cubesPerRow; y++)
                {
                    for (int x = 0; x < cubesPerRow; x++)
                    {

                        _basicEffect.World = Matrix.CreateRotationY(_rotation) * _worldMatrix *
                                             Matrix.CreateTranslation(offset - new Vector3(x, -z, y) * cubeSeperaration);

                        foreach (var pass in _basicEffect.CurrentTechnique.Passes)
                        {
                            pass.Apply();
                            GraphicsDevice.DrawPrimitives(PrimitiveType.TriangleList, 0, 12);
                        }
                    }
                }
            }
        }
    }
}

```

**Comment by georg-eckert-zeiss** [comment] 2021-08-18 08:45
I could reproduce it very often using this scene:

```csharp
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using MonoGame.Framework.WpfInterop;
using MonoGame.Framework.WpfInterop.Input;
using System.Windows;
using WpfTest.Components;

namespace WpfTest.Scenes
{
    /// <summary>
    /// Displays content that heavily benefits from msaa (or any sort of filtering really) and lets the user toggle msaa on and off.
    /// </summary>
    public class MsaaScene : WpfGame
    {
        private WpfKeyboard _keyboard;
        private KeyboardState _keyboardState;
        private Matrix _projectionMatrix;
        private Matrix _viewMatrix;
        private Matrix _worldMatrix;
        private bool _disposed;

        private TextComponent _msaaMessage;
        private WpfGraphicsDeviceService _graphicsDeviceService;

        private Model _model;
        private float _rotation;

        protected override void LoadContent()
        {
            base.LoadContent();

            _model = Content.Load<Model>("StumpyTree");
        }

        protected override void Initialize()
        {
            _disposed = false;
            _graphicsDeviceService = new WpfGraphicsDeviceService(this)
            {
                PreferMultiSampling = true
            };
            Components.Add(new FpsComponent(this));
            Components.Add(new TimingComponent(this));
            _msaaMessage = new TextComponent(this, GetMsaaMessage(), new Vector2(1, 0), HorizontalAlignment.Right);
            Components.Add(_msaaMessage);

            float tilt = MathHelper.ToRadians(0);  // 0 degree angle
            // Use the world matrix to tilt the cube along x and y axes.
            _worldMatrix = Matrix.CreateRotationX(tilt) * Matrix.CreateRotationY(tilt);
            _viewMatrix = Matrix.CreateLookAt(new Vector3(40, 20, 40), new Vector3(20, 0, 20), Vector3.Up);

            RefreshProjection();

            _keyboard = new WpfKeyboard(this);

            base.Initialize();
        }

        private string GetMsaaMessage() => $"MSAA is {(_graphicsDeviceService.PreferMultiSampling ? "On" : "Off")}, press space to toggle";

        protected override void Dispose(bool disposing)
        {
            if (_disposed)
                return;

            Components.Clear();
            _disposed = true;

            base.Dispose(disposing);
        }

        /// <summary>
        /// Update projection matrix values, both in the calculated matrix <see cref="_projectionMatrix"/>.
        /// </summary>
        private void RefreshProjection()
        {
            _projectionMatrix = Matrix.CreatePerspectiveFieldOfView(
                MathHelper.ToRadians(45), // 45 degree angle
                (float)GraphicsDevice.Viewport.Width /
                (float)GraphicsDevice.Viewport.Height,
                1.0f, 100.0f);
        }

        protected override void Update(GameTime gameTime)
        {
            var previousKeyboardState = _keyboardState;
            _keyboardState = _keyboard.GetState();

            if (_keyboardState.IsKeyDown(Keys.Space) &&
                previousKeyboardState.IsKeyUp(Keys.Space))
            {
                _graphicsDeviceService.PreferMultiSampling = !_graphicsDeviceService.PreferMultiSampling;
                _graphicsDeviceService.ApplyChanges();

                _msaaMessage.Text = GetMsaaMessage();

            }
            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            //The projection depends on viewport dimensions (aspect ratio).
            // Because WPF controls can be resized at any time (user resizes window)
            // we need to refresh the values each draw call, otherwise cube will look distorted to user
            RefreshProjection();

            GraphicsDevice.Clear(Color.CornflowerBlue);
            GraphicsDevice.DepthStencilState = DepthStencilState.Default;
            GraphicsDevice.RasterizerState = RasterizerState.CullNone;

            if (IsActive)
                _rotation += (float)gameTime.ElapsedGameTime.TotalMilliseconds / 1000 * MathHelper.TwoPi / 4;

            DrawModel(_model, _rotation);

            base.Draw(gameTime);
        }

        private void DrawModel(Model model, float modelRotation)
        {
            const float cubeSeperaration = 2;
            const int cubesPerRow = 20;


            // Copy any parent transforms.
            Matrix[] transforms = new Matrix[model.Bones.Count];
            model.CopyAbsoluteBoneTransformsTo(transforms);

            // really bad performance, could use instancing to improve performance a lot
            for (int y = 0; y < cubesPerRow; y++)
            {
                for (int x = 0; x < cubesPerRow; x++)
                {
                    // Draw the model. A model can have multiple meshes, so loop.
                    foreach (ModelMesh mesh in model.Meshes)
                    {
                        // This is where the mesh orientation is set, as well as our camera and projection.
                        foreach (BasicEffect effect in mesh.Effects)
                        {
                            SetPolygonalLighting(effect);
                            effect.World = transforms[mesh.ParentBone.Index] 
                                           * Matrix.CreateRotationY(modelRotation)
                                           * Matrix.CreateScale(0.01f)
                                           * Matrix.CreateTranslation(new Vector3(x, 0, y)*cubeSeperaration)
                                           * _worldMatrix;
                            
                            effect.View = _viewMatrix;
                            effect.Projection = _projectionMatrix;
                        }

                        // Draw the mesh, using the effects set above.
                        mesh.Draw();
                    }
                }
            }
        }

        private void SetPolygonalLighting(BasicEffect basicEffect)
        {
            // really ugly way of getting the model lit up (green color only), but does the job for now

            // primitive color
            basicEffect.AmbientLightColor = new Vector3(0.1f, 0.1f, 0.1f);
            basicEffect.DiffuseColor = new Vector3(1.0f, 1.0f, 1.0f);
            basicEffect.SpecularColor = new Vector3(0.25f, 0.25f, 0.25f);
            basicEffect.SpecularPower = 2.0f;
            basicEffect.Alpha = 1.0f;

            basicEffect.LightingEnabled = true;
            if (basicEffect.LightingEnabled)
            {
                // x direction
                basicEffect.DirectionalLight1.DiffuseColor = new Vector3(0, 0.75f, 0);
                basicEffect.DirectionalLight1.Direction = Vector3.Normalize(new Vector3(-1, -1, 0));
                // points from the light to the origin of the scene
                basicEffect.DirectionalLight0.SpecularColor = Vector3.One;

                basicEffect.DirectionalLight1.Enabled = true;
                // y direction
                basicEffect.DirectionalLight1.DiffuseColor = new Vector3(0, 0.75f, 0);
                basicEffect.DirectionalLight1.Direction = Vector3.Normalize(new Vector3(-1, -1, 0));
                basicEffect.DirectionalLight1.SpecularColor = Vector3.One;
            }
        }
    }
}

```

**Comment by georg-eckert-zeiss** [comment] 2021-08-18 09:20
Might be related to the flickering during scaling, which still exists.

**Comment by MarcStan** [comment] 2021-08-19 21:34
Thanks for the research and the links.

I can also reproduce the flickering even with a dedicated GPU (when pressing space to toggle the MSAA on/off) with your last scene.
Even though the GPU is not under full load the WPF interface reacts sluggishly because of the amount of rendering that is happening.
I assume the branch with [frame skipping](https://github.com/MarcStan/monogame-framework-wpfinterop/issues/23#issuecomment-663640147) didn't help much either?

At the end of the day I'm at the mercy of the WPF rendering pipeline as proper swapchains are not supported. So I don't think this can be fixed inside this library.

**Comment by georg-eckert-zeiss** [comment] 2021-08-20 08:12
Thanks for your fast answer. The frameskipping branch unfortunately does not work for that. Seems to be a synchronisation issue between D3DImage and WPF. Yeah. I too guess thats a difficult problem to solve.

**Comment by georg-eckert-zeiss** [comment] 2021-08-20 13:18
@MarcStan  before abandoning these, you might want to have a look at [this explanation](https://github.com/microsoft/WPFDXInterop/issues/27#issuecomment-247837100) - if you haven't already : D.

**Comment by MarcStan** [comment] 2021-08-20 16:44
Yeah I'm already using both [locking & double buffering](https://github.com/MarcStan/monogame-framework-wpfinterop/blob/580220dcfaf36f6ae1a026bd203025761a477436/MonoGame.Framework.WpfInterop/D3D11Host.cs#L561-L570). Unless my implementation is wrong this didn't fix it. (I also tried to remove the double buffering as suggested by weltkante but that didn't fix it either).

**Comment by georg-eckert-zeiss** [comment] 2021-08-23 06:33
I'll further investigate. If I figure it out, I'll make a PR. But right now it does not look very promising : (

Best regards,
Georg

**Comment by georg-eckert-zeiss** [comment] 2021-08-25 06:40
Did some more research on the topic. It seems that `GraphicsDevice.Flush()` is async. Therefore it can happen, that Flush is not done, when `Unlock()` is called. Therefore a blank/black frame is copied over to the front buffer. I found the comment of someone who was able to fix the issue, using `Direct3D11.Device.ImmediateContext.ResolveSubresource`. He was however using SharpDX's graphics device and I could not figure out yet, how to get a hold of it from MonoGame. But this seems to be the solution. Hope it's possible to use it with MonoGame.

[Thread at Stackoverflow](https://stackoverflow.com/questions/27894051/need-sharpdxelement-alternative-workaround-to-sharpdx-wpf-flickering). Answer should be the last comment.

**Comment by georg-eckert-zeiss** [comment] 2021-08-25 06:47
To verify this, you can add `Thread.Sleep(10)` right after `GraphicsDevice.Flush()`. That gets rid of the black frames. Of course this is not a solution.

**Comment by georg-eckert-zeiss** [comment] 2021-08-25 10:08
I think I managed to get rid of the flickering. I had to use Reflection to get the SharpDX device for that. Unfortunately the MSAA scenes do not work now. I'll post some some tomorrow.

**Comment by MarcStan** [comment] 2021-08-29 17:12
I tested your PR and it looks good. v1.9.1 with it should go live soon.

Thanks for your help investigating and creating the PR!

**Closed by MarcStan** 2021-08-29 17:12 UTC
